# Generated by Django 4.1.7 on 2023-04-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('priority', models.CharField(choices=[('A', 'High'), ('B', 'Medium'), ('C', 'Low')], max_length=1)),
                ('date', models.DateField()),
                ('travelbag', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=1000)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
            ],
        ),
    ]
