# Generated by Django 4.1.7 on 2023-05-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_todolist_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
