# Generated by Django 4.1.7 on 2023-05-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_todolist_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=4000)),
                ('rating', models.CharField(choices=[('Awesome', 'Awesome'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Not Bad', 'Not Bad'), ('Bad', 'Bad')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='planner',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20),
        ),
    ]
